# H2 Database configuration
server:
  port: 9090

# H2 Console configuration
h2:
  console:
    path: /h2-console
#    settings:
#      web-allow-others: true

spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    initalization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false #true visar hibernates sql-körningar
    properties:
      hibernate:
        format_sql: true
        ddl:
          auto: create

 #sql:
   #init:
     #mode: always

#jpa:
  #hibernate:
    #ddl-auto: create

# Add logging
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

#jpa:
  #defer-datasource-initialization: true
#batch:
   #jdbc:
     #initialize-schema: always
     #table-prefix: BATCH_
     #schema: classpath:org/springframework/batch/core/schema.sql

# Gör så att batch inte startar automatiskt
# spring:
#   batch:
#     job:
#       enabled: false

#application:
#  schedule:
#    cron: "0 0 0/5 * * * ?"
#  batch:
#    chunkSize: 100
